// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHet8sy_QgF2f8guvUjCVpXTx0ZC52jw',
    appId: '1:540202946044:web:e3d60f9b48969987667679',
    messagingSenderId: '540202946044',
    projectId: 'running-c7122',
    authDomain: 'running-c7122.firebaseapp.com',
    storageBucket: 'running-c7122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDBXDC_NMEAZxfFrHXtmbkkDPAMbRpJhs',
    appId: '1:540202946044:android:2cb13ac7cbfbc451667679',
    messagingSenderId: '540202946044',
    projectId: 'running-c7122',
    storageBucket: 'running-c7122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc6HcloknVcF_unmpU3LRbcpP0tgWzXAs',
    appId: '1:540202946044:ios:3e54e4597601e07d667679',
    messagingSenderId: '540202946044',
    projectId: 'running-c7122',
    storageBucket: 'running-c7122.appspot.com',
    iosBundleId: 'com.example.running',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc6HcloknVcF_unmpU3LRbcpP0tgWzXAs',
    appId: '1:540202946044:ios:c7c2b482f2a7af18667679',
    messagingSenderId: '540202946044',
    projectId: 'running-c7122',
    storageBucket: 'running-c7122.appspot.com',
    iosBundleId: 'com.example.running.RunnerTests',
  );
}
